<?php
global $twigPrimaryAreas;


				$options = array("Accident Reconstruction",
"Accident Reconstruction/Fire",
"Accounting",
"Animals/Veterinarian",
"Anthropology",
"Audio/Video",
"Boating/Maritime",
"Cannabis/Marijuana",
"Chemical Dependence",
"Computers/Cell Phones/Digital Evidence",
"Criminology/Gangs",
"Dentistry",
"DNA",
"Document Examination/Handwriting Analysis",
"Elder/Disability Issues",
"Fingerprints",
"Fire Investigation/Firearms/Weapons",
"Forensics/Crime Scene/Ballistics/Blood Spatter",
"Forensics/Medical/Toxicology",
"Immigration",
"Infant/Child Medical",
"Intellectual Property",
"Interpreter",
"Interrogations & Confession",
"Jury & Trial Consultant",
"Knives",
"Law Enforcement/Use of Force/Prison/Corrections",
"Medical",
"Mitigation/Investigation",
"Neuropsychology",
"Neuropsychology/Cross-Cultural",
"Nonverbal Communication",
"Pathology",
"Polygraph",
"All Psych",
"Psych/Clinical",
"Psych/Forensic Evaluator",
"Psych/Forensic Evaluator/Cross-Cultural",
"All Psychiatry",
"Psychiatry/Child",
"Psychiatry/Forensic",
"Psychiatry/Gender/Trans",
"All Psychology",
"Psychology/Child Welfare",
"Psychology/Clinical",
"Psychology/Cross-Cultural",
"Psychology/General",
"Psychology/Mental Health",
"Psychology/Sex Offenders",
"Sex Offenders",
"Speech/Language Pathology");



			$values = array("Accident Reconstruction",
"Accident Reconstruction/Fire",
"Accounting",
"Animals/Veterinarian",
"Anthropology",
"Audio/Video",
"Boating/Maritime",
"Cannabis/Marijuana",
"Chemical Dependence",
"Computers/Cell Phones/Digital Evidence",
"Criminology/Gangs",
"Dentistry",
"DNA",
"Document Examination/Handwriting Analysis",
"Elder/Disability Issues",
"Fingerprints",
"Fire Investigation/Firearms/Weapons",
"Forensics/Crime Scene/Ballistics/Blood Spatter",
"Forensics/Medical/Toxicology",
"Immigration",
"Infant/Child Medical",
"Intellectual Property",
"Interpreter",
"Interrogations & Confession",
"Jury & Trial Consultant",
"Knives",
"Law Enforcement/Use of Force/Prison/Corrections",
"Medical",
"Mitigation/Investigation",
"Neuropsychology",
"Neuropsychology/Cross-Cultural",
"Nonverbal Communication",
"Pathology",
"Polygraph",
"Psych",
"Psych/Clinical",
"Psych/Forensic Evaluator",
"Psych/Forensic Evaluator/Cross-Cultural",
"Psychiatry",
"Psychiatry/Child",
"Psychiatry/Forensic",
"Psychiatry/Gender/Trans",
"Psychology",
"Psychology/Child Welfare",
"Psychology/Clinical",
"Psychology/Cross-Cultural",
"Psychology/General",
"Psychology/Mental Health",
"Psychology/Sex Offenders",
"Sex Offenders",
"Speech/Language Pathology");



$twigPrimaryAreas = array_map(function($v,$o){
	$obj = new stdClass();
	$obj->value = $v;
	$obj->option = $o;
	return $obj;
},$values,$options);